name: my-web-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install PNPM
              run: |
                  sudo apt install npm
                  npm i --location=global pnpm@8

            - name: Install Depedencies
              run: make install

            - name: Install MongoDB
              run: make install-mongo

            - name: Start MongoDB
              run: make start-mongo

            - name: Migrate Document
              run: |
                  sleep 1.5
                  make migrate-mongo

            - name: Run Code Generation
              run: make generate

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  ORIGIN: http://0.0.0.0:3000
                  NEXT_PUBLIC_ORIGIN: http://0.0.0.0:3000
                  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: hi
                  MONGO_DB: myWeb
                  MONGO_COLLECTION_CONTACT_FORM_MESSAEG: contactFormMessage
                  MONGO_ADDRESS: localhost
                  MONGO_PORT: 27017
                  MONGO_USER: runner
                  MONGO_PASSWORD: mongodb
              run: make test

            - name: Run Build
              env:
                  NEXT_PUBLIC_ORIGIN: http://0.0.0.0:3000
                  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: hi
              run: make build
